modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/decce6/${modid}/issues"
license = "${mod_license}"

[[mods]]
    authors = "decce"
    description = '''${mod_description}'''
    displayName = "${mod_name}"
    displayURL = "https://modrinth.com/mod/${modid}"
    logoFile = "${modid}.png"
    logoBlur = false
    modId = "${modid}"
    version = "${mod_version_full}"

[[dependencies.${modid}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modid}]]
    modId = "minecraft"
    versionRange = "${minecraft_supported_forge}"
    type = "required"